version: '3.8'

services:
  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-reverb
    ports:
      - "10000:10000" # Expose Reverb WebSocket port (matching what's used on Render)
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      REVERB_APP_ID: your_app_id
      REVERB_APP_KEY: your_app_key
      REVERB_APP_SECRET: your_app_secret
    command: ["php", "artisan", "reverb:start", "--host=0.0.0.0", "--port=10000"]

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
